name: Build and Push Docker Image on Release

on:
  release:
    types: [published]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - name: Check out the code
        uses: actions/checkout@v4
      
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract release tag
        id: extract_release
        run: echo "RELEASE_TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Build and push Docker image - Static
        uses: docker/build-push-action@v6
        with:
            context: .
            push: true
            target: static
            build-args: |
                TARGET=static
            platforms: linux/amd64, linux/arm64
            tags: |
                ghcr.io/b4iterdev/valo-map-veto-static:latest
                ghcr.io/b4iterdev/valo-map-veto-static:${{ env.RELEASE_TAG }}
      - name: Build and push Docker image - Server
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          target: server
          platforms: linux/amd64, linux/arm64
          tags: |
            ghcr.io/b4iterdev/valo-map-veto-server:latest
            ghcr.io/b4iterdev/valo-map-veto-server:${{ env.RELEASE_TAG }} 
        